# Generated by Django 5.2.6 on 2025-09-23 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern', models.TextField()),
                ('rule_type', models.CharField(choices=[('sql_injection', 'SQL Injection'), ('xss', 'Cross-Site Scripting'), ('path_traversal', 'Path Traversal'), ('rate_limit', 'Rate Limiting'), ('bot_detection', 'Bot Detection'), ('custom', 'Custom Pattern')], max_length=50)),
                ('action', models.CharField(choices=[('BLOCK', 'Block'), ('ALLOW', 'Allow'), ('LOG', 'Log Only')], default='BLOCK', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField()),
                ('backend_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('admin_level', models.CharField(blank=True, choices=[('super', 'Super Admin'), ('support', 'Support Admin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('url', models.URLField()),
                ('method', models.CharField(max_length=10)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('BLOCKED', 'Blocked'), ('ALLOWED', 'Allowed'), ('RATE_LIMITED', 'Rate Limited')], max_length=20)),
                ('response_time', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rule_matched', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waf_proxy.rule')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waf_proxy.site')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waf_proxy.user'),
        ),
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('request_count', models.IntegerField(default=1)),
                ('window_start', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waf_proxy.site')),
            ],
            options={
                'unique_together': {('site', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='SiteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('custom_action', models.CharField(blank=True, choices=[('BLOCK', 'Block'), ('ALLOW', 'Allow'), ('LOG', 'Log Only')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waf_proxy.rule')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waf_proxy.site')),
            ],
            options={
                'unique_together': {('site', 'rule')},
            },
        ),
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_requests', models.IntegerField(default=0)),
                ('blocked_requests', models.IntegerField(default=0)),
                ('allowed_requests', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waf_proxy.site')),
            ],
            options={
                'unique_together': {('site', 'date')},
            },
        ),
    ]
