# Generated by Django 5.2.6 on 2025-09-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf_proxy', '0002_user_last_login_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(max_length=255),
        ),
    ]
