# Generated by Django 5.2.6 on 2025-09-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf_proxy', '0005_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
